uploads = []
outputs = []

[[generated]]
id = "TWHtRLjvw6RBl4_d5hIe6"
uri = "file://artifacts/hannah-brooks/public/logo-hb.png"
type = "image"
title = "HB monogram luxury logo"

[[generated]]
id = "RetPaMUR3uj77c5dY7Kqi"
uri = "file://artifacts/hannah-brooks/public/logo-banner.png"
type = "image"
title = "Hannah Brooks banner logo"

[[generated]]
id = "4uv4XZgk32wif5O7aocAe"
uri = "file://artifacts/hannah-brooks/public/logo-sr.png"
type = "image"
title = "sophie rain logo monogram"

[[generated]]
id = "_kpPw_YnNCPUU8kb1_G3_"
uri = "file://artifacts/hannah-brooks/public/sophie-avatar.png"
type = "image"
title = "sophie rain avatar portrait"

[[generated]]
id = "nVhqxu2AL_MxtoXG7Dt6U"
uri = "file://artifacts/hannah-brooks/public/sophie-chat-avatar.png"
type = "image"
title = "sophie chat avatar close up"
